### ISSUE TITLE
代码报错问题

### ISSUE THREAD

**Issue by Jmkiy** [lyyf2002/ASGEA#1]
<img width="830" alt="22a4fc70371d995a96ad1b7e6a05385" src="https://github.com/lyyf2002/ASGEA/assets/56023704/e17ef3a2-3ce7-4803-90ff-405932f7bbcd">
![image](https://github.com/lyyf2002/ASGEA/assets/56023704/118c2581-0aac-4de2-a105-2f185bc66240)

这里说到张量不对，cat不起来，每次都是到52%就报错。3个数据集都是这个错误，想问问作者这是什么问题，以及如何修改。

**Comment by Jmkiy** [comment]
<img width="272" alt="07b478f4bf0325552546d48e0939cbd" src="https://github.com/lyyf2002/ASGEA/assets/56023704/7854a11c-d16a-459f-aa62-a6de4a39f046">

**Comment by lyyf2002** [comment]
我这里好像并没有出现这个问题呀，请问你是使用我的sh脚本启动的吗

**Comment by Jmkiy** [comment]
是的，在vscode使用bash run.sh FB

**Comment by lyyf2002** [comment]
能否print一下edges拼接之前是什么呢？我怀疑是其中edges在挖取子图时没有获得到边，为空，导致这个edges的shape和其他的不一样，也许是由于环境不一样，但是我这个集群没有办法复现你的bug。如果还是无法解决问题的话 ，请邮箱私信我，也许我可以远程帮你看看是什么问题。

**Comment by Jmkiy** [comment]
你好，不好意思再次打扰了，请问可以帮我远程看看那个出错问题吗？（尝试了一些方法好像都是那里出问题。）





MilestTones
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lyyf2002/ASGEA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月17日(星期天) 下午5:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lyyf2002/ASGEA] 代码报错问题 (Issue #1)





 
能否print一下edges拼接之前是什么呢？我怀疑是其中edges在挖取子图时没有获得到边，为空，导致这个edges的shape和其他的不一样，也许是由于环境不一样，但是我这个集群没有办法复现你的bug。如果还是无法解决问题的话 ，请邮箱私信我，也许我可以远程帮你看看是什么问题。

**Comment by lyyf2002** [comment]
我的邮箱是luoyyf@act.buaa.edu.cn

**Comment by lyyf2002** [comment]
问题解决了，torch的版本不对，请使用README中所写的1.12版本torch
